version: '3.8'

services:
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - '5000:5000'
    volumes:
      - type: bind
        source: ./backend
        target: /opt/app/backend

    depends_on:
      - keycloak

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - backend


  keycloak:
    container_name: keycloak
    build:
      context: ./keycloak
      dockerfile: keycloak.dockerfile
    ports:
      - '8080:8080'
  